#print("Hello, World!")
#print('Naim'*2)
#a = input()
#print(a)
print("Hey, Man! What is your name?")
name=input()
print("Nice to meet you, "+name)
print("How old are you, Buddy?")
age=input()
birth_year=2022-int(age)
answer=str(birth_year)
print("You were born in "+answer)
